### PR TITLE
v0.9.0.1

### PR DESCRIPTION
**Pull request by jjr840430**
Generated `go` file with HCL configuration options while compiling

### CODE REVIEW

**Comment by jjr840430** [comment]
@ronaldtse Can you please review this pull request?
It's related to [this issue](https://github.com/riboseinc/kaohi/issues/20)

**Comment by ronaldtse** [comment]
@jjr840430 can you move the file `gen_config.go` to go-multiconfig?

i.e. generate config.mel.go inside Kaohi project directory using a command like:
```
go-multiconfig -generate config.mel
```

Thanks!

**Comment by jjr840430** [comment]
@ronaldtse I moved `genconfig` into `go-multiconfig`.
The pull request in `go-multiconfig` is [here](https://github.com/riboseinc/go-multiconfig/pull/8)

**Comment by ronaldtse** [comment]
@jjr840430 will you merge this? Thanks!

**Comment by jjr840430** [comment]
@ronaldtse Merged!

**Pull request merged**
